const GET_RECIPES = 'GET_RECIPES';
const CREATE_RECIPES = 'CREATE_RECIPES';
const GET_DIETS = 'GET_DIETS';
const SEARCH_RECIPES = 'SEARCH_RECIPES';
const ORDER = 'ORDER';
const FILTER = 'FILTER';
const CHANGE_PAGE = 'CHANGE_PAGE';
const GET_RECIPES_DB = 'GET_RECIPES_DB';

module.exports = {
    GET_RECIPES,
    CREATE_RECIPES,
    SEARCH_RECIPES,
    ORDER,
    FILTER,
    CHANGE_PAGE,
    GET_DIETS,
    GET_RECIPES_DB
}
